config/routes.rb
Rails.application.routes.draw do

  root to: 'contributions#top'
  resources :contributions do
    collection do
      post :confirm1
    end
  end

  resources :users do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :caption, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :contributions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_conts, through: :favorites, source: :contribution
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:edit, :update, :show, :destroy]
  before_action :force_top, only: [:new, :show, :edit]

  def top
    if current_user.nil?
    else
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @contributions = Contribution.all
  end

  def new
    if params[:back]
      @contribution = Contribution.new(contribution_params)
    else
      @contribution = Contribution.new
    end
  end

  def create
    @contribution = Contribution.new(contribution_params)
    @contribution.user_id = current_user.id
    @cache = params[:cache][:image]

    if @cache.empty?
    else
      @contribution.image.retrieve_from_cache! @cache
    end

    if @contribution.save
      InsMailer.contribution_mail(@contribution).deliver
      redirect_to user_path(@contribution.user_id)
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(contribution_id: @contribution.id)
  end

  def edit
  end

  def update
    if @contribution.update(contribution_params)
      redirect_to user_path(current_user.id), notice: '投稿を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @contribution.destroy
    redirect_to user_path(current_user.id), notice: '投稿を削除しました'
  end

  def confirm1
    @contribution = Contribution.new(contribution_params)
    @contribution.user_id = current_user.id
    render :new if @contribution.invalid?
  end

  private

  def contribution_params
    params.require(:contribution).permit(:image, :caption)
  end

  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  def force_top
    if current_user.nil?
      redirect_to  new_session_path, notice: "ログインしてください"
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(contribution_id: params[:contribution_id])
    redirect_to user_path(current_user.id)
  end

  def destroy
    favorite = current_user.favorites.find_by(contribution_id: params[:contribution_id]).destroy
    redirect_to user_path(current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  def index
  end

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    @cache = params[:cache][:image]

    if @cache.empty?
    else
      @user.image.retrieve_from_cache! @cache
    end

    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def show
    @contributions = @user.contributions
    @favorite_conts = @user.favorite_conts
  end

  def edit
  end

  def update
    if @user.update(user_edit_params)
      redirect_to @user, notice: "更新しました"
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :image)
  end
  def user_edit_params
    params.require(:user).permit(:name, :email, :image)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
  def choosen_new_or_edit
    if action_name == 'new' || action_name == 'confirm1'
      confirm1_contributions_path
    elsif action_name == 'edit'
      contribution_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_users_path
    elsif action_name == 'edit'
      user_path
    end
  end
end

app/views/contributions/_form.html.erb
<% if @contribution.errors.any? %>
  <div id="error_explanation">
    <h2><%= @contribution.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @contribution.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @contribution, local: true, url: choosen_new_or_edit ) do |f| %>
  <div class="contribution_image">
    <%= f.label :image %>
    <%= f.file_field :image, id: :feed_image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="contibution_caption">
    <%= f.label :caption %>
    <%= f.text_field :caption %>
  </div>
  <%= f.submit %>
<% end %>

app/views/contributions/confirm1.html.erb
<h3>以下の内容で登録しますか？</h3>

<%= form_with(model: @contribution, local:true, url: contributions_path ) do |f| %>
  <%= f.hidden_field :caption %>

  <p>画像：<%= image_tag(@contribution.image) %></p>
  <%= hidden_field_tag :"cache[image]",@contribution.image.cache_name %>
  <p>キャプション：<%= @contribution.caption %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_with(model: @contribution, url: new_contribution_path, local: true, method: 'get') do |f| %>
  <%= f.hidden_field :caption %>
  <%= f.submit "戻る", name: 'back' %>
<% end %>

app/views/contributions/edit.html.erb
<p>投稿の編集</p>
<%= render 'form' %>
<%= link_to "一覧に戻る", user_path(current_user.id) %>

app/views/contributions/index.html.erb
<div class="container">
  <div class="row">
    <% @contributions.each do |c| %>
    <div class="col-xs-12 col-sm-6 col-md-4 cont_img">
      <%= link_to image_tag(c.image),contribution_path(c.id) %>
    </div>
    <% end %>
  </div>
</div>

app/views/contributions/new.html.erb
<p>新規投稿</p>
<%= render 'form' %>

app/views/contributions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5"><%= image_tag(@contribution.image) %></div>
    <div class="col-xs-7">
      <div>投稿者名：<%= @contribution.user.name %></div>
      <div>キャプション：<%= @contribution.caption %></div>
      <% if @contribution.user == current_user %>
        <div class="show_elm"><%= link_to "投稿を編集する", edit_contribution_path, type: "button", class: "btn-info"  %></div>
        <div class="show_elm"><%= link_to "投稿を削除する", contribution_path(@contribution.id),
                                    method: :delete, data: { confirm: '本当に削除していいですか？' }, type: "button", class: "btn-danger"  %></div>
      <% else %>
        <% if @favorite.present? %>
          <div class="show_elm"><%= link_to 'お気に入り解除する', favorite_path(contribution_id: @contribution.id), method: :delete, type: "button", class: "btn-info" %></div>
        <% else %>
          <div class="show_elm"><%= link_to "お気に入りに登録する", favorites_path(contribution_id: @contribution.id), method: :post, type: "button", class: "btn-info" %></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/contributions/top.html.erb
<div class="top_site">
  <div class="center-block top_elem">InsClone</div>
  <div class="center-block top_elem">友達の写真や動画をチェックしよう</div>
  <div class="center-block top_elem"><%= link_to "ログイン", new_session_path %></div>
  <div class="center-block top_elem"><%= link_to "新規登録", new_user_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <header>

        <div class="header">
          <% if logged_in? %>
            <div type="btn" class="pull-right btn-success header_elm"><%= link_to "プロフィール", user_path(current_user.id) %></div>
            <%= link_to image_tag('insclone.png'), root_path %>
            <div type="btn" class="pull-left btn-success header_elm"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></div>
          <% else %>
            <div type="btn" class="pull-right btn-success header_elm"><%= link_to "新規登録", new_user_path %></div>
            <%= link_to image_tag('insclone.png'), root_path %>
            <div type="btn" class="pull-left btn-success header_elm"><%= link_to "ログイン", new_session_path %></div>
          <% end %>
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
        </div>
      </header>
      <div id="contents">
      <%= yield %>
      </div>
      <footer class="row">
        <% if logged_in? %>
          <!-- <div class="col-xs-3"><%= link_to "ログアウト", session_path(current_user.id), method: :delete, type: "btn", class: "btn-success btn-lg" %></div>
          <div class="col-xs-3"><%= link_to "投稿一覧", contributions_path, type: "btn", class: "btn-success btn-lg"  %></div>
          <div class="col-xs-3"><%= link_to "新規投稿", new_contribution_path, type: "btn", class: "btn-success btn-lg"  %></div>
          <div class="col-xs-3"><%= link_to "プロフィール", user_path(current_user.id), type: "btn", class: "btn-success btn-lg" %></div> -->

          <div type="btn"  class="col-xs-3 btn-success btn-lg"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></div>
          <div type="btn"  class="col-xs-3 btn-success btn-lg"><%= link_to "投稿一覧", contributions_path  %></div>
          <div type="btn"  class="col-xs-3 btn-success btn-lg"><%= link_to "新規投稿", new_contribution_path %></div>
          <div type="btn"  class="col-xs-3 btn-success btn-lg"><%= link_to "プロフィール", user_path(current_user.id) %></div>
        <% end %>

      </footer>
    </div>
  </body>
</html>

app/views/users/confirm.html.erb
<h3>以下の内容で登録しますか？</h3>

<%= form_with(model: @user, local:true) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :password %>
  <%= f.hidden_field :password_confirmation %>

  <p>名前：<%= @user.name %></p>
  <p>メールアドレス：<%= @user.email %></p>
  <p>プロフィール画像：<%= image_tag(@user.image) %></p>
  <%= hidden_field_tag :"cache[image]",@user.image.cache_name %>
  <p>パスワードは表示しません</p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_with(model: @user, url: new_user_path, local: true, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.submit "戻る", name: 'back' %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local:true ) do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :image %></td>
      <td><%= f.file_field :image, id: :user_image %></td>
      <%= f.hidden_field :image_cache %>
    </tr>
  </table>
  <%= f.submit "アカウント情報を変更します" %>
  <% end %>

app/views/users/new.html.erb
<h1>新規作成</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true,url: choose_new_or_edit) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image, id: :feed_image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div><%= f.submit "登録します" %></div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="profbox">
      <div class="row">
        <div class="col-xs-4"><%= image_tag(@user.image, :class => "img-circle") %></div>
        <div class="col-xs-8">
          <div class="row user_prof"><%= @user.name %>のページ</div>
          <div class="row user_prof">メールアドレス: <%= @user.email %></div>
          <div class="row user_prof"><%= link_to "ユーザー情報を変更する", edit_user_path(@user),type: "button",class: "btn btn-success btn-block"  %></div>
        </div>
      </div>
  </div>
  <div class="row row-eq-height">
    自分の投稿一覧
    <table>
      <% @contributions.each do |con| %>
        <tr class="col-xs-12 col-sm-6 col-md-4 cont_img">
          <td><%= link_to image_tag(con.image), contribution_path(con.id) %></td>
          <!-- <td><%= con.caption %></td> -->
        </tr>
      <% end %>
  </table>
  </div>
  <div class="row">
    お気に入り一覧
    <table>
    <% @favorite_conts.each do |con| %>
      <tr class="col-xs-12 col-sm-6 col-md-4 cont_img">
        <td><%= link_to image_tag(con.image), contribution_path(con.id) %></td>
        <!-- <td><%= con.caption %></td> -->
      </tr>
    <% end %>
    </table>
  </div>
</div>